### ISSUE TITLE
Error creating file LibSize.txt

### ISSUE THREAD

**Issue by borshago** [LiuzLab/PolyA-miner#3]
Hi,

Running polyaminer with the arguments -d, -o, -pa, -index, -bed, -c1, -c2, and -fasta, and 4 samples, gives the following error:

> Traceback (most recent call last):
>   File "PolyA-miner-master/PolyA-miner.py", line 231, in <module>
>     main()
>   File "PolyA-miner-master/PolyA-miner.py", line 182, in main
>     if MakeMatrix.MakeMatrix(args.o, args.p, args.key, args.pa_p, args.pa_a, args.pa_m, controls, treated, args.apa_min, args.gene_min, lf) == 1:
>   File "PolyA-miner-master/lib/MakeMatrix.py", line 96, in MakeMatrix
>     fwls.write("\n"+"\t".join(result))
> TypeError: sequence item 0: expected str instance, NoneType found

Adding the code "print(result)" to MakeMatrix.py before line 95 revealed result to be the list [None,None,None,None] (I have 4 samples). The issue was that in my version of subread (2.0.1), featureCounts output does not have the line "Total reads : " but "Total alignments : ". After making the change "Total reads : " -> "Total alignments : " in MakeMatrix.py line 73, the run finished without error.

Should the library sizes be calculated from the total reads/alignments, though? If I think about all the RNA-seq workflows I've seen and used, the library sizes are usually calculated from the successfully assigned reads/alignments (the ones that contribute to the gene expression count vectors of samples). What are your thoughts on this?

Best regards,
Daniel

**Comment by hari-yalamanchili** [comment]
Hi Daniel,

Thank you for posting the issue. This is very helpful especially for the users with different featureCounts/subread versions. To clarify, the current version of PolyA-miner was tested with featureCounts v1.6.0. I will make a note of this and roll out an edit.

Regarding library size, I agree that one should use mapped reads to normalize (like RPKM/TPM). PolyA-miner abstracts each polyadenylated (PA) site as the proportion of reads mapped to a specific PA site of the total reads mapped to all the PA sites (of a gene). This will minimize any potential normalization bias due to varying internal priming (mapped reads but due to genomic "A" stretches) levels and other noisy sites across the samples. In brief, PolyA-miner uses total reads to get size fraction estimates and later normalize PA sites as the proportions of mapped reads. 

Best,
Hari

**Comment by hari-yalamanchili** [comment]
Updated test environment and featureCounts version dependency fixed.
