### ISSUE TITLE
So so so many bugs in PolyA-miner!!!!! 

### ISSUE THREAD

**Issue by ericjason11111** [LiuzLab/PolyA-miner#5]
So many bugs in PolyA-miner!!!!!

**Comment by hari-yalamanchili** [comment]
Hi Eric... Thank you for your interest in PolyA-miner. I am sorry to hear that you encountered hiccups in execution. Can you share the error log/screenshot ? Also, what version of bedtools and featureCounts are you using? We can start from here.

**Comment by hyunhwan-jeong** [comment]
Hi, @hari-yalamanchili, I might be wrong, but I guess @ericjason11111 might ask how to solve issue #4. Based on @ericjason11111's comment at #4, it seems that he doesn't have a problem executing PolyA-miner. You may need to figure out how to solve #4.

Dear @ericjason11111, I know facing problems while running a Github software could be frustrating, but I don't think it is a great idea to open an issue to blame, rather than figuring out any solution to your problems. Please let @hari-yalamanchili know details of your problems. 

Hyun-Hwan Jeong

**Comment by hari-yalamanchili** [comment]
@ericjason11111 .... Bedtools-merge version behavior issues are fixed in the recent update. 
Thanks!
